// --------------------------------------------------------------------------------------------------------------------
// <auto-generated>
//   Generated using OBeautifulCode.CodeGen.ModelObject (1.0.54.0)
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Compression.Test
{
    using System.CodeDom.Compiler;
    using System.Diagnostics.CodeAnalysis;

    using FakeItEasy;
    
    using OBeautifulCode.Assertion.Recipes;

    using Xunit;

    [ExcludeFromCodeCoverage]
    [GeneratedCode("OBeautifulCode.CodeGen.ModelObject", "1.0.54.0")]
    public static partial class CompressionDummyFactoryTest
    {
        [Fact]
        public static void CompressionDummyFactory___Should_derive_from_DefaultCompressionDummyFactory___When_reflecting()
        {
            // Arrange
            var dummyFactoryType = typeof(CompressionDummyFactory);

            var defaultDummyFactoryType = typeof(DefaultCompressionDummyFactory);

            // Act, Assert
            defaultDummyFactoryType.GetInterface(nameof(IDummyFactory)).AsTest().Must().NotBeNull();

            dummyFactoryType.BaseType.AsTest().Must().BeEqualTo(defaultDummyFactoryType);
        }
    }
}